// soroban.ts — the only file that imports from the generated contract bindings.
// All components call these wrappers; nothing imports @stellar/stellar-sdk directly. (AGENTS.md)
// Transaction pattern: AssembledTransaction.signAndSend() — D-007 revised.

import { rpc as SorobanRpc } from 'ticket';
import { Client as TicketClient } from 'ticket';
import { Client as MarketplaceClient } from 'marketplace';

import {
  TICKET_CONTRACT_ID,
  MARKETPLACE_CONTRACT_ID,
  NETWORK_PASSPHRASE,
  RPC_URL,
} from './constants';
import type { Event, Ticket, SignFn } from '../types';

// ─── Contract error maps ──────────────────────────────────────────────────────
// Maps on-chain error codes to user-readable messages.

const TICKET_ERRORS: Record<number, string> = {
  1:  'This contract is already initialized.',
  2:  'Contract not initialized — contact support.',
  3:  'Event not found.',
  4:  'This event is no longer active.',
  5:  'This event is sold out.',
  6:  'Event has not been cancelled — refund not available.',
  7:  'Funds cannot be released yet (event date not passed).',
  8:  'Funds have already been released for this event.',
  9:  'Ticket not found.',
  10: 'This ticket has already been used.',
  11: 'You do not own this ticket.',
  12: 'Only the event organizer can perform this action.',
  13: 'Only the marketplace contract can perform this action.',
  14: 'Insufficient escrow balance.',
  15: 'Arithmetic overflow — contact support.',
  16: 'Arithmetic underflow — contact support.',
  17: 'Division by zero — contact support.',
  18: 'An event with this ID already exists.',
  19: 'Event capacity must be greater than zero.',
  20: 'Ticket price must be greater than zero.',
  21: 'Event date must be in the future.',
  22: 'A ticket with this ID already exists.',
};

const MARKETPLACE_ERRORS: Record<number, string> = {
  1:  'Marketplace already initialized.',
  2:  'Marketplace not initialized.',
  3:  'Listing not found.',
  4:  'This listing is no longer open.',
  5:  'A listing with this ID already exists.',
  6:  'Ask price must be greater than zero.',
  7:  'Only the original seller can perform this action.',
  8:  'You cannot buy your own listing.',
  9:  'Arithmetic overflow — contact support.',
  10: 'Arithmetic underflow — contact support.',
  11: 'Division by zero — contact support.',
  12: 'Ticket ownership changed — listing is stale.',
};

// ─── Client factories ─────────────────────────────────────────────────────────

function getTicketClient(publicKey: string): TicketClient {
  return new TicketClient({
    contractId: TICKET_CONTRACT_ID,
    networkPassphrase: NETWORK_PASSPHRASE,
    rpcUrl: RPC_URL,
    publicKey,
  });
}

function getMarketplaceClient(publicKey: string): MarketplaceClient {
  return new MarketplaceClient({
    contractId: MARKETPLACE_CONTRACT_ID,
    networkPassphrase: NETWORK_PASSPHRASE,
    rpcUrl: RPC_URL,
    publicKey,
  });
}

// ─── Error extraction ─────────────────────────────────────────────────────────

function extractErrorMessage(err: unknown, errorMap: Record<number, string>): string {
  if (err instanceof Error) {
    // The SDK surfaces contract errors as messages containing the error code
    const match = err.message.match(/Error\(Contract, #(\d+)\)/);
    if (match) {
      const code = parseInt(match[1], 10);
      return errorMap[code] ?? `Contract error #${code}.`;
    }
    return err.message;
  }
  return 'An unexpected error occurred.';
}

// ─── Write functions (require signing) ───────────────────────────────────────

export interface CreateEventParams {
  eventId: string;
  name: string;
  dateUnix: number;
  capacityXlm: number;     // raw capacity (ticket count)
  priceStroops: bigint;    // price in stroops — use xlmToStroops() from types
}

/**
 * Purchase a ticket for an event.
 * ticketId is generated by the caller (generateID() from lib/utils.ts).
 */
export async function purchaseTicket(
  eventId: string,
  buyerPublicKey: string,
  ticketId: string,
  signFn: SignFn
): Promise<void> {
  const client = getTicketClient(buyerPublicKey);
  try {
    const tx = await client.purchase({ event_id: eventId, buyer: buyerPublicKey, ticket_id: ticketId });
    await tx.signAndSend({ signTransaction: signFn });
  } catch (err) {
    throw new Error(extractErrorMessage(err, TICKET_ERRORS));
  }
}

/**
 * Create a new event on-chain.
 * eventId is generated by the caller (generateID() from lib/utils.ts).
 */
export async function createEvent(
  params: CreateEventParams,
  organizerPublicKey: string,
  signFn: SignFn
): Promise<void> {
  const client = getTicketClient(organizerPublicKey);
  try {
    const tx = await client.create_event({
      organizer: organizerPublicKey,
      event_id: params.eventId,
      name: params.name,
      date_unix: BigInt(params.dateUnix),
      capacity: BigInt(params.capacityXlm),
      price_per_ticket: params.priceStroops,
    });
    await tx.signAndSend({ signTransaction: signFn });
  } catch (err) {
    throw new Error(extractErrorMessage(err, TICKET_ERRORS));
  }
}

/**
 * Release escrowed funds to the organizer after the event date.
 */
export async function releaseFunds(
  eventId: string,
  organizerPublicKey: string,
  signFn: SignFn
): Promise<void> {
  const client = getTicketClient(organizerPublicKey);
  try {
    const tx = await client.release_funds({ event_id: eventId, organizer: organizerPublicKey });
    await tx.signAndSend({ signTransaction: signFn });
  } catch (err) {
    throw new Error(extractErrorMessage(err, TICKET_ERRORS));
  }
}

/**
 * Cancel an event. Pull-based refunds — attendees call refundTicket() individually. (D-002)
 */
export async function cancelEvent(
  eventId: string,
  organizerPublicKey: string,
  signFn: SignFn
): Promise<void> {
  const client = getTicketClient(organizerPublicKey);
  try {
    const tx = await client.cancel_event({ event_id: eventId, organizer: organizerPublicKey });
    await tx.signAndSend({ signTransaction: signFn });
  } catch (err) {
    throw new Error(extractErrorMessage(err, TICKET_ERRORS));
  }
}

/**
 * Mark a ticket as used at the venue door. Only callable by the event organizer.
 * Called AFTER the QR signature has been verified locally. (D-005)
 */
export async function markUsed(
  ticketId: string,
  organizerPublicKey: string,
  signFn: SignFn
): Promise<void> {
  const client = getTicketClient(organizerPublicKey);
  try {
    const tx = await client.mark_used({ ticket_id: ticketId, organizer: organizerPublicKey });
    await tx.signAndSend({ signTransaction: signFn });
  } catch (err) {
    throw new Error(extractErrorMessage(err, TICKET_ERRORS));
  }
}

/**
 * Refund a ticket after an event cancellation. Pull-based — attendee calls this. (D-002)
 */
export async function refundTicket(
  ticketId: string,
  attendeePublicKey: string,
  signFn: SignFn
): Promise<void> {
  const client = getTicketClient(attendeePublicKey);
  try {
    const tx = await client.refund({ ticket_id: ticketId, attendee: attendeePublicKey });
    await tx.signAndSend({ signTransaction: signFn });
  } catch (err) {
    throw new Error(extractErrorMessage(err, TICKET_ERRORS));
  }
}

// ─── Marketplace write functions ──────────────────────────────────────────────

/**
 * Create a secondary-market listing for a ticket.
 * listingId is generated by the caller (generateID()).
 */
export async function listTicket(
  sellerPublicKey: string,
  listingId: string,
  ticketId: string,
  eventId: string,
  askPriceStroops: bigint,
  signFn: SignFn
): Promise<void> {
  const client = getMarketplaceClient(sellerPublicKey);
  try {
    const tx = await client.list_ticket({
      seller: sellerPublicKey,
      listing_id: listingId,
      ticket_id: ticketId,
      event_id: eventId,
      ask_price: askPriceStroops,
    });
    await tx.signAndSend({ signTransaction: signFn });
  } catch (err) {
    throw new Error(extractErrorMessage(err, MARKETPLACE_ERRORS));
  }
}

/**
 * Purchase a secondary-market listing.
 */
export async function buyListing(
  sellerPublicKey: string,
  listingId: string,
  buyerPublicKey: string,
  signFn: SignFn
): Promise<void> {
  const client = getMarketplaceClient(buyerPublicKey);
  try {
    const tx = await client.buy_listing({
      seller: sellerPublicKey,
      listing_id: listingId,
      buyer: buyerPublicKey,
    });
    await tx.signAndSend({ signTransaction: signFn });
  } catch (err) {
    throw new Error(extractErrorMessage(err, MARKETPLACE_ERRORS));
  }
}

/**
 * Cancel a secondary-market listing. Only the original seller can cancel.
 */
export async function cancelListing(
  sellerPublicKey: string,
  listingId: string,
  signFn: SignFn
): Promise<void> {
  const client = getMarketplaceClient(sellerPublicKey);
  try {
    const tx = await client.cancel_listing({ seller: sellerPublicKey, listing_id: listingId });
    await tx.signAndSend({ signTransaction: signFn });
  } catch (err) {
    throw new Error(extractErrorMessage(err, MARKETPLACE_ERRORS));
  }
}

// ─── Read-only functions (no signing required) ────────────────────────────────

// Uses a dummy public key for read-only calls — the SDK requires one for the
// client constructor, but simulation-only calls don't submit a transaction.
const READ_ONLY_KEY = 'GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN';

/**
 * Fetch a single event's current on-chain state by ID.
 * Returns null if the event does not exist.
 */
export async function getEvent(eventId: string): Promise<Event | null> {
  const client = getTicketClient(READ_ONLY_KEY);
  try {
    const tx = await client.get_event({ event_id: eventId });
    const result = tx.result;
    if (!result || result.isErr()) return null;

    const e = result.unwrap();
    return {
      eventId,
      organizer: e.organizer,
      name: e.name,
      dateUnix: Number(e.date_unix),
      capacity: Number(e.capacity),
      pricePerTicket: Number(e.price_per_ticket),
      currentSupply: Number(e.current_supply),
      status: e.status.tag as Event['status'],
    };
  } catch {
    return null;
  }
}

/**
 * Fetch a single ticket's current on-chain state by ID.
 * Returns null if the ticket does not exist.
 */
export async function getTicket(ticketId: string): Promise<Ticket | null> {
  const client = getTicketClient(READ_ONLY_KEY);
  try {
    const tx = await client.get_ticket({ ticket_id: ticketId });
    const result = tx.result;
    if (!result || result.isErr()) return null;

    const t = result.unwrap();
    return {
      ticketId,
      eventId: t.event_id,
      owner: t.owner,
      status: t.status.tag as Ticket['status'],
    };
  } catch {
    return null;
  }
}

// ─── RPC event helpers (used by useEvents and useTickets hooks) ───────────────
// Re-exported so hooks import from here — not directly from the SDK. (D-029)

export { SorobanRpc };

export function getRpcServer(): SorobanRpc.Server {
  return new SorobanRpc.Server(RPC_URL);
}
